import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Marquee from "@/components/Marquee";
import { ToastContainer } from "react-toastify";

const notoSansBangali = Noto_Sans_Bengali({
 
  subsets: ["latin","bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSansBangali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <Marquee />
        <ToastContainer
  position="bottom-right"
  autoClose={3000}
  hideProgressBar={true}
   style={{ zIndex: 999999 }}
/>
        {children}
        </body>
    </html>
  );
}
